insert into `geo_pais` (`id`, `nombre`, `sup`, `geo`) values (32, "Bolivia", 777, 0);
insert into `geo_departamento` (`id`, `nombre`, `sup`, `geo`) values (8, "Beni", 32, 1);
insert into `geo_provincia` (`nombre`, `sup`, `geo`) values ("Cercado", 8, 2);
insert into `geo_municipio` (`nombre`, `sup`, `geo`) values ("San Javier", 1, 3);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (2532, "Espíritu Santo", 1, 4);
insert into `geo_recinto` (`nombre`, `sup`, `geo`) values ("Escuela Espiritu Santo", 2532, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80411, "1", 1, 5);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (3867, "La Curva", 1, 4);
insert into `geo_recinto` (`nombre`, `sup`, `geo`) values ("U.E. La Curva", 3867, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80419, "1", 2, 5);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (3126, "Laguna Colorada", 1, 4);
insert into `geo_recinto` (`nombre`, `sup`, `geo`) values ("Escuela Laguna Colorada", 3126, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80417, "1", 3, 5);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (2539, "Nueva Israel", 1, 4);
insert into `geo_recinto` (`nombre`, `sup`, `geo`) values ("Escuela Nueva Israel", 2539, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80414, "1", 4, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80415, "2", 4, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80416, "3", 4, 5);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (3340, "Pedro Ignacio Muiba", 1, 4);
insert into `geo_recinto` (`nombre`, `sup`, `geo`) values ("Escuela Pedro Ignacio Muiba", 3340, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80418, "1", 5, 5);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (2530, "San Javier", 1, 4);
insert into `geo_recinto` (`nombre`, `sup`, `geo`) values ("Escuela San Javier", 2530, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80409, "1", 6, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80410, "2", 6, 5);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (2535, "San Pedro", 1, 4);
insert into `geo_recinto` (`nombre`, `sup`, `geo`) values ("Escuela San Pedro", 2535, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80412, "1", 7, 5);
insert into `geo_mesa` (`id`, `nombre`, `sup`, `geo`) values (80413, "2", 7, 5);
insert into `geo_localidad` (`id`, `nombre`, `sup`, `geo`) values (4172, "Villa Rodeo", 1, 4);